idf_component_register(
    SRCS 
        "main.c"
        "Business_Logic/system_state.c"
        "Networking_Services/app_mqtt_client.c"
        "Networking_Services/tg_bot.c"
        "Networking_Services/wifi_app.c"
        "Peripheral/coin_acceptor.c"
        "Peripheral/display_7seg.c"
        "Peripheral/display_tft.c"
        "Peripheral/encoder.c"
        "Peripheral/qr_code.c"
    INCLUDE_DIRS 
        "."
        "Business_Logic"
        "Networking_Services"
        "Peripheral"
    REQUIRES 
        esp-tls
        esp_event 
        esp_wifi 
        esp_timer
        esp_http_server 
        esp_driver_gpio
        esp_driver_spi
        nvs_flash 
        driver
        qrcode
        mqtt
)
